"""
HYDRA V4 — Setup and Run
========================

Reads keys from `Desktop\\API_KEYS\\ALL KEYS AND TOKENS.txt` LOCALLY,
writes `secrets\\.env` LOCALLY, then runs the replay.

Nothing leaves the laptop. No prints contain secret values.
"""

from __future__ import annotations
import os
import re
import sys
from pathlib import Path


def mask(s: str) -> str:
    if not s:
        return "(none)"
    if len(s) <= 4:
        return "*" * len(s)
    return "..." + s[-4:]


def parse_keys(content: str) -> dict[str, str | None]:
    """Return dict with anthropic / oanda_token / oanda_account / oanda_env."""

    out = {
        "anthropic_key": None,
        "oanda_token": None,
        "oanda_account": None,
        "oanda_env": "live",
    }

    # 1. Anthropic key — sk-ant-...
    m = re.search(r"sk-ant-[A-Za-z0-9_\-]{20,}", content)
    if m:
        out["anthropic_key"] = m.group(0)

    # 2. OANDA account id — NNN-NNN-NNNNNNNN-NNN
    m = re.search(r"\d{3}-\d{3}-\d{8}-\d{3}", content)
    if m:
        out["oanda_account"] = m.group(0)

    # 3. OANDA token — try labels first
    label_patterns = [
        r"(?im)OANDA[_\s\-]*API[_\s\-]*TOKEN\s*[:=]\s*([A-Za-z0-9\-]{30,})",
        r"(?im)OANDA[_\s\-]*TOKEN\s*[:=]\s*([A-Za-z0-9\-]{30,})",
        r"(?im)OANDA[_\s\-]*BEARER\s*[:=]\s*([A-Za-z0-9\-]{30,})",
        r"(?im)OANDA[_\s\-]*KEY\s*[:=]\s*([A-Za-z0-9\-]{30,})",
        r"(?im)BEARER[_\s\-]*TOKEN\s*[:=]\s*([A-Za-z0-9\-]{30,})",
        r"(?im)API[_\s\-]*TOKEN\s*[:=]\s*([A-Za-z0-9\-]{30,})",
    ]
    for pat in label_patterns:
        for cand in re.findall(pat, content):
            if cand != out["anthropic_key"]:
                out["oanda_token"] = cand
                break
        if out["oanda_token"]:
            break

    # 4. Fallback: hex-shaped 40-90 char token (typical OANDA token)
    if not out["oanda_token"]:
        for m in re.finditer(r"\b[a-f0-9\-]{40,90}\b", content):
            v = m.group(0)
            if v == out["anthropic_key"]:
                continue
            if v == out["oanda_account"]:
                continue
            out["oanda_token"] = v
            break

    # 5. OANDA env hint
    m = re.search(r"(?im)OANDA[_\s]*ENV\s*[:=]\s*(practice|live|demo)", content)
    if m:
        out["oanda_env"] = m.group(1).lower()

    return out


def write_env(env_path: Path, parsed: dict[str, str | None], source_hint: str) -> None:
    env_path.parent.mkdir(parents=True, exist_ok=True)
    body = (
        "# HYDRA V4 - Local secrets (gitignored)\n"
        f"# Auto-generated by setup_and_run.py from: {source_hint}\n"
        "# This file MUST NOT be committed or shared.\n"
        "\n"
        f"ANTHROPIC_API_KEY={parsed['anthropic_key']}\n"
        f"OANDA_API_TOKEN={parsed['oanda_token']}\n"
        f"OANDA_ACCOUNT_ID={parsed['oanda_account']}\n"
        f"OANDA_ENV={parsed['oanda_env']}\n"
    )
    env_path.write_text(body, encoding="utf-8")


def ensure_gitignore(proj: Path) -> None:
    gi = proj / ".gitignore"
    needed = ["secrets/.env\n", "replay_results/\n", "data_cache/\n"]
    existing = gi.read_text(encoding="utf-8") if gi.exists() else ""
    additions = [line for line in needed if line.strip() not in existing]
    if additions:
        with gi.open("a", encoding="utf-8") as f:
            if existing and not existing.endswith("\n"):
                f.write("\n")
            f.writelines(additions)


def main() -> int:
    print("=" * 60)
    print(" HYDRA V4 - Setup and Run (LOCAL ONLY)")
    print("=" * 60)
    print()

    desktop = Path(os.environ["USERPROFILE"]) / "Desktop"
    proj = desktop / "HYDRA V4"
    keys_file = desktop / "API_KEYS" / "ALL KEYS AND TOKENS.txt"
    env_file = proj / "secrets" / ".env"

    if not proj.exists():
        print(f"[X] HYDRA V4 not found at: {proj}")
        return 1
    print(f"[OK] HYDRA V4 at: {proj}")

    if not keys_file.exists():
        print(f"[X] Keys file not found at: {keys_file}")
        return 1
    print(f"[OK] Keys file: {keys_file}")
    print()

    # Read keys file LOCALLY
    print("[*] Reading keys file (locally, content not displayed) ...")
    content = keys_file.read_text(encoding="utf-8", errors="replace")
    print(f"[OK] Read {len(content)} chars")
    print()

    # Parse
    print("[*] Parsing keys ...")
    parsed = parse_keys(content)
    print(f"      ANTHROPIC_API_KEY: {mask(parsed['anthropic_key'])}")
    print(f"      OANDA_API_TOKEN:   {mask(parsed['oanda_token'])}")
    print(f"      OANDA_ACCOUNT_ID:  {parsed['oanda_account'] or '(none)'}")
    print(f"      OANDA_ENV:         {parsed['oanda_env']}")
    print()

    missing = []
    if not parsed["anthropic_key"]:
        missing.append("ANTHROPIC_API_KEY")
    if not parsed["oanda_token"]:
        missing.append("OANDA_API_TOKEN")
    if not parsed["oanda_account"]:
        missing.append("OANDA_ACCOUNT_ID")

    if missing:
        print(f"[X] Could not auto-detect: {', '.join(missing)}")
        print()
        print("    Open your keys file in Notepad and check the format.")
        print("    Expected formats:")
        print("      Anthropic key starting with: sk-ant-...")
        print("      OANDA Account ID like:       NNN-NNN-NNNNNNNN-NNN")
        print("      OANDA token: a long hex/alphanumeric string after 'OANDA_TOKEN' or similar.")
        print()
        print("    OR open the .env template manually and paste values:")
        env_file.parent.mkdir(parents=True, exist_ok=True)
        if not env_file.exists():
            env_file.write_text(
                "# Replace REPLACE_ME with real values\n"
                "ANTHROPIC_API_KEY=sk-ant-REPLACE_ME\n"
                "OANDA_API_TOKEN=REPLACE_ME\n"
                "OANDA_ACCOUNT_ID=001-001-XXXXXXXX-001\n"
                "OANDA_ENV=live\n",
                encoding="utf-8",
            )
        print(f"      Template at: {env_file}")
        return 2

    # Write .env LOCALLY
    print("[*] Writing secrets/.env ...")
    write_env(env_file, parsed, source_hint=str(keys_file))
    print(f"[OK] Wrote {env_file}")
    print()

    # Update .gitignore
    ensure_gitignore(proj)
    print("[OK] .gitignore updated")
    print()

    # Optionally run replay
    print("=" * 60)
    print(" Setup complete.")
    print("=" * 60)
    print()
    answer = input(" Run the 2-year replay now? (Y/n) ").strip().lower()
    if answer in ("", "y", "yes"):
        print()
        print(" Running replay (will take 30-60 minutes on first run)...")
        print(" =" * 30)
        # Load env vars into this process
        for line in env_file.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                k, v = line.split("=", 1)
                os.environ[k.strip()] = v.strip()

        # Open a log file that captures EVERYTHING (stdout + stderr).
        # NO secrets are printed by run_live_replay (it uses a logger, and
        # secret_redactor is on the bridge), so the log is safe to share.
        log_path = desktop / "HYDRA_REPLAY.log"
        log_fh = open(log_path, "w", encoding="utf-8")
        print(f" Logging full output to: {log_path}")
        print(f" (Safe to share with Claude — no secrets printed by replay code.)")
        print()

        class TeeOutput:
            def __init__(self, *streams):
                self.streams = streams
            def write(self, s):
                for st in self.streams:
                    try:
                        st.write(s)
                        st.flush()
                    except Exception:
                        pass
            def flush(self):
                for st in self.streams:
                    try:
                        st.flush()
                    except Exception:
                        pass

        original_stdout = sys.stdout
        original_stderr = sys.stderr
        sys.stdout = TeeOutput(original_stdout, log_fh)
        sys.stderr = TeeOutput(original_stderr, log_fh)

        # Import and run
        sys.path.insert(0, str(proj))
        try:
            import runpy
            runpy.run_path(str(proj / "run_live_replay.py"), run_name="__main__")
        except SystemExit as e:
            sys.stdout = original_stdout
            sys.stderr = original_stderr
            log_fh.close()
            print(f"\n Replay finished with exit code: {e.code}")
            print(f" Full log: {log_path}")
            return int(e.code) if isinstance(e.code, int) else 1
        except Exception as e:
            print(f"\n[X] Replay error: {type(e).__name__}: {e}")
            import traceback
            traceback.print_exc()
            sys.stdout = original_stdout
            sys.stderr = original_stderr
            log_fh.close()
            print(f"\n Full log saved at: {log_path}")
            print(f" Send the log content to Claude for diagnosis.")
            # Also open it
            try:
                os.startfile(str(log_path))  # type: ignore
            except Exception:
                pass
            return 3
        finally:
            sys.stdout = original_stdout
            sys.stderr = original_stderr
            try: log_fh.close()
            except Exception: pass

    print()
    print(" Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
